2025-05-21 20:57:23,027 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 20:57:45,788 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 20:57:46,803 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:02:47,220 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:03:09,979 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:03:11,006 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:19:14,436 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:19:37,267 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:19:38,291 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:24:38,328 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:25:01,108 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:25:02,119 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:30:02,749 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:30:25,535 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:30:26,554 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:35:26,814 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:35:49,503 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:35:50,526 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 21:40:52,319 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 21:41:15,254 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 21:41:16,270 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 22:02:08,910 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 22:02:31,731 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 22:02:32,751 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 22:17:33,562 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 22:17:56,306 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 22:17:57,323 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 22:32:57,709 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 22:33:20,493 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 22:33:21,514 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 22:48:22,515 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 22:48:45,329 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 22:48:46,348 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 23:03:46,821 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 23:04:09,513 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 23:04:10,536 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 23:19:11,489 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 23:19:34,212 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 23:19:35,234 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 23:34:35,842 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 23:34:58,703 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 23:34:59,720 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-21 23:50:00,116 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-21 23:50:22,846 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-21 23:50:23,863 - alerting.telegram_bot - INFO - Đã gửi 1/1 cảnh báo bất thường
2025-05-22 00:08:51,297 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 00:09:13,977 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 00:09:37,198 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 00:10:00,407 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 00:10:23,716 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 00:10:24,737 - alerting.telegram_bot - INFO - Đã gửi 4/4 cảnh báo bất thường
2025-05-22 00:27:35,058 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 00:27:56,725 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4DFDF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:28:17,806 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4DF580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:28:38,906 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4D7670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:28:59,990 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39778FA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:28:59,992 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 00:46:16,179 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 00:46:37,869 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B397788E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:46:58,929 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4CC4C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:47:20,023 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3ADA2310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:47:41,106 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4DF760>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 00:47:41,108 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 01:04:55,875 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 01:05:17,518 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39AD3640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:05:38,608 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39770430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:05:59,687 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3978E850>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:06:20,765 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39AED490>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:06:20,767 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 01:23:37,099 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 01:23:58,744 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39830DF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:24:19,830 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39770C40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:24:40,932 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39770E50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:25:02,001 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39AEDBB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:25:02,003 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 01:42:17,256 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 01:42:38,909 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39AEDEE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:42:59,977 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A36C700>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:43:21,075 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A36CCD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:43:42,165 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39770F70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 01:43:42,167 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 02:00:56,975 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 02:01:18,662 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3674A520>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:01:39,743 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A078CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:02:00,841 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3AD960D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:02:21,918 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A070F70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:02:21,920 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 02:19:37,104 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 02:19:58,697 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39780730>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:20:19,798 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A0706D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:20:40,875 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B38A974F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:21:01,942 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3AD96A90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:21:01,943 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 02:38:18,184 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 02:38:39,800 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3674A820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:39:00,864 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A0703D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:39:21,950 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3AD96EB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:39:43,030 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A3ABF10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:39:43,032 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 02:56:58,773 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 02:57:20,445 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BBCA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:57:41,547 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BBDC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:58:02,644 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C220130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:58:23,738 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A44F4C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 02:58:23,740 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 03:15:39,155 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 03:16:00,817 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BBCA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:16:21,908 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C5BF130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:16:42,978 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C2209A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:17:04,072 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C220DC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:17:04,073 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 03:34:19,300 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 03:34:40,915 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C220E80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:35:02,013 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BB7F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:35:23,060 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BB820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:35:44,140 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A44F700>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:35:44,142 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 03:53:01,011 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 03:53:22,685 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C220670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:53:43,758 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B367BB190>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:54:04,821 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3ADC1460>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:54:25,918 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C5BF370>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 03:54:25,920 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 04:12:10,984 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 04:12:32,621 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B397562E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:12:53,715 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B36757FD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:13:14,789 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B36757B20>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:13:35,883 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3976EB20>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:13:35,885 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 04:30:51,361 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 04:31:13,049 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B36757250>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:31:34,129 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3ADA3040>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:31:55,240 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3976E4C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:32:16,322 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3976E7F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:32:16,324 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 04:49:31,634 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 04:49:53,240 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B397565B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:50:14,315 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B36757C70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:50:35,392 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3ADA3220>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:50:56,461 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39A93220>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 04:50:56,463 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 05:08:12,301 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 05:08:33,960 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A08DFA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:08:55,049 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A08D130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:09:16,140 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A375D00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:09:37,222 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A074D00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:09:37,224 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 05:26:52,951 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 05:27:14,558 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B368BA7C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:27:35,643 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A08DB20>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:27:56,736 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A375430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:28:17,818 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A375130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:28:17,820 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 05:45:33,170 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 05:45:54,787 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A375A90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:46:15,880 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A08DF40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:46:36,962 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B368BAB80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:46:58,033 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B36A4B910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 05:46:58,035 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 06:04:12,910 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 06:04:34,596 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DD4220>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:04:55,681 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A505100>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:05:16,767 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A505D60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:05:37,845 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E3DD90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:05:37,847 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 06:22:53,246 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 06:23:14,972 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DD48E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:23:36,053 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E3D850>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:23:57,143 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398FAC40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:24:18,232 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A505FD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:24:18,234 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 06:41:33,597 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 06:41:55,267 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398BF9D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:42:16,357 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E3D160>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:42:37,450 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398FA820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:42:58,546 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DD4280>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 06:42:58,548 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 07:00:13,516 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 07:00:35,147 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39870AC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:00:56,243 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399388B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:01:17,328 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E0FCD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:01:38,423 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3985FBE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:01:38,425 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 07:18:53,742 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 07:19:15,370 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E0F7F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:19:36,451 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39938790>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:19:57,522 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39870FA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:20:18,584 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3985F370>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:20:18,586 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 07:37:33,798 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 07:37:55,402 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399381F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:38:16,498 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3985F1C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:38:37,590 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3985F400>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:38:58,683 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E0FAF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:38:58,685 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 07:56:13,796 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 07:56:35,489 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39E0F7C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:56:56,563 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399385B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:57:17,644 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3990AEB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:57:38,728 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3985FB50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 07:57:38,730 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 08:15:23,511 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 08:15:45,189 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DECFA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:16:06,271 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398B5BB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:16:27,353 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398B52E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:16:48,453 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3678EC70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:16:48,455 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 08:34:03,735 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 08:34:25,371 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DEC130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:34:46,446 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A428A30>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:35:07,550 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A428CA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:35:28,641 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3678E550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:35:28,643 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 08:52:43,985 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 08:53:05,639 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DEC4C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:53:26,735 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A4282E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:53:47,831 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398B50D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:54:08,898 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B398B5A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 08:54:08,900 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 09:11:25,098 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 09:11:46,738 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399978E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:12:07,821 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39997490>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:12:28,921 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DD4640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:12:50,015 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A51A250>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:12:50,017 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 09:30:05,261 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 09:30:26,890 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39997E50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:30:47,979 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399971C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:31:09,048 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3992C0D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:31:30,142 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A51A2E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:31:30,144 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 09:48:46,423 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 09:49:08,035 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B399971C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:49:29,119 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3992C4F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:49:50,204 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3A51AD00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:50:11,301 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B39DD0B80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 09:50:11,303 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 10:07:27,222 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 10:07:48,854 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B369F2C70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 10:08:09,944 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3642BB50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 10:08:31,027 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3C568A30>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 10:08:52,103 - alerting.telegram_bot - ERROR - Lỗi khi gửi tin nhắn đến Telegram: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8100234231:AAHo-DXBkQoGb804GzXlQ36Y4YvJPFZD4LY/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B3ADC2E50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2025-05-22 10:08:52,105 - alerting.telegram_bot - INFO - Đã gửi 0/4 cảnh báo bất thường
2025-05-22 10:23:53,050 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 10:24:16,259 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:24:40,060 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:25:03,705 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:25:27,405 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:25:28,420 - alerting.telegram_bot - INFO - Đã gửi 4/4 cảnh báo bất thường
2025-05-22 10:40:28,827 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 10:40:52,163 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:41:15,836 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:41:39,611 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:41:40,638 - alerting.telegram_bot - INFO - Đã gửi 3/3 cảnh báo bất thường
2025-05-22 10:56:41,377 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 10:57:05,179 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:57:28,887 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:57:52,910 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 10:57:53,924 - alerting.telegram_bot - INFO - Đã gửi 3/3 cảnh báo bất thường
2025-05-22 11:12:54,619 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 11:13:17,968 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:13:41,548 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:14:05,312 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:14:06,331 - alerting.telegram_bot - INFO - Đã gửi 3/3 cảnh báo bất thường
2025-05-22 11:29:06,729 - alerting.telegram_bot - INFO - Khởi tạo Telegram Bot
2025-05-22 11:29:30,065 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:29:53,770 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:30:17,451 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:30:41,180 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:31:04,856 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:31:28,522 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:31:52,207 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:32:16,044 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:32:39,736 - alerting.telegram_bot - INFO - Đã gửi tin nhắn đến Telegram thành công
2025-05-22 11:32:40,758 - alerting.telegram_bot - INFO - Đã gửi 9/9 cảnh báo bất thường
